### ISSUE TITLE
[Bug] Setup Bug with the Windows 

### ISSUE THREAD

**Issue by VOSID8** [scalacenter/scaladex#1369]
### Current behavior

Following [the setup guide](https://github.com/scalacenter/scaladex/blob/main/CONTRIBUTING.md), on `sbt:scaladex> data/run init` I am facing 

> [error] stack trace is suppressed; run last infra / Compile / startPostgres for the full output
[error] stack trace is suppressed; run last infra / startElasticsearch for the full output
[error] (infra / Compile / startPostgres) java.lang.UnsupportedOperationException
[error] (infra / startElasticsearch) java.lang.UnsupportedOperationException
[error] Total time: 1 s, completed 15 Mar, 2024 3:36:03 PM
[info] new client connected: network-1

On running `last infra / startElasticsearch` , I discovered problem with POSIX permissions on data folder for Elasticsearch

> sbt:scaladex> last infra / startElasticsearch
[error] java.lang.UnsupportedOperationException
[error]         at java.nio.file.Files.setPosixFilePermissions(Files.java:2044)
[error]         at sbt.io.RichNioPath.setPermissions(Path.scala:130)
[error]         at sbt.io.RichNioPath.setPermissions$(Path.scala:129)
[error]         at sbt.io.RichFile.setPermissions(Path.scala:34)
[error]         at sbt.io.IO$.setPermissions(IO.scala:1274)
[error]         at Elasticsearch$.startContainer(Elasticsearch.scala:62)
[error]         at Elasticsearch$.$anonfun$settings$3(Elasticsearch.scala:39)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error]         at Elasticsearch$.$anonfun$settings$1(Elasticsearch.scala:49)
[error]         at Elasticsearch$.$anonfun$settings$1$adapted(Elasticsearch.scala:26)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49) at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.Execute.work(Execute.scala:292)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:283) at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:26)
at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
[error] (infra / startElasticsearch) java.lang.UnsupportedOperationException

I then switched to WSL2 and did `data/run init` to populate the database but faced 
![image](https://github.com/scalacenter/scaladex/assets/91724657/fc183e3d-2eaa-4369-b521-ddba5c4370bc)
![image](https://github.com/scalacenter/scaladex/assets/91724657/3663f96e-4e8b-4975-ae55-441651fdc450)

### Expected Behavior

It should have populated the database successfully.

### Extra comments

I am on Windows 10, and using VSCode with Metals with JDK 11. Further I've been using the same images been asked for in the guide for the Docker.

**Comment by ayushkoli772** [comment]
@VOSID8 in the logs it says "Timeout waiting for container" so I think you should try increasing the timeout for `Postgres` container
