### ISSUE TITLE
Internal server error when searching

### ISSUE THREAD

**Issue by jvican** [scalacenter/scaladex#196]
Looking up 'NOT' in the search box results in an internal server error, probably because it's a special keyword used for filtering. In such case, not filters are not working.

This has to do with the indexer? /cc @MasseGuillaume

**Comment by jvican** [comment]
Yeah, indeed:
```
scaladexJVM [ERROR] [07/19/2016 11:16:49.999] [scaladex-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(scaladex)] Error during processing of request HttpRequest(HttpMethod(GET),http://localhost:8080/search?q=NOT,List(Host: localhost:8080, User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0, Accept: text/html, application/xhtml+xml, application/xml;q=0.9, */*;q=0.8, Accept-Language: en-US, en;q=0.5, Accept-Encoding: gzip, deflate, Referer: http://localhost:8080/, Connection: keep-alive, Timeout-Access: <function1>),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
scaladexJVM Failed to execute phase [query], all shards failed; shardFailures {[Q8hNolH5QJ2EtpZNcls6GA][scaladex][0]: RemoteTransportException[[Abe Brown][local[1]][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":10,"query":{"bool":{"should":[{"term":{"repository":"NOT"}},{"term":{"organization":"NOT"}},{"term":{"keywords":"NOT"}},{"term":{"github.description":"NOT"}},{"term":{"github.readme":"NOT"}},{"query_string":{"query":"NOT"}}]}},"sort":[{"_score":{}}]}]]; nested: QueryParsingException[Failed to parse query [NOT]]; nested: ParseException[Cannot parse 'NOT': Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; nested: ParseException[Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; }{[Q8hNolH5QJ2EtpZNcls6GA][scaladex][1]: RemoteTransportException[[Abe Brown][local[1]][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":10,"query":{"bool":{"should":[{"term":{"repository":"NOT"}},{"term":{"organization":"NOT"}},{"term":{"keywords":"NOT"}},{"term":{"github.description":"NOT"}},{"term":{"github.readme":"NOT"}},{"query_string":{"query":"NOT"}}]}},"sort":[{"_score":{}}]}]]; nested: QueryParsingException[Failed to parse query [NOT]]; nested: ParseException[Cannot parse 'NOT': Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; nested: ParseException[Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; }{[Q8hNolH5QJ2EtpZNcls6GA][scaladex][2]: RemoteTransportException[[Abe Brown][local[1]][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":10,"query":{"bool":{"should":[{"term":{"repository":"NOT"}},{"term":{"organization":"NOT"}},{"term":{"keywords":"NOT"}},{"term":{"github.description":"NOT"}},{"term":{"github.readme":"NOT"}},{"query_string":{"query":"NOT"}}]}},"sort":[{"_score":{}}]}]]; nested: QueryParsingException[Failed to parse query [NOT]]; nested: ParseException[Cannot parse 'NOT': Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; nested: ParseException[Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; }{[Q8hNolH5QJ2EtpZNcls6GA][scaladex][3]: RemoteTransportException[[Abe Brown][local[1]][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":10,"query":{"bool":{"should":[{"term":{"repository":"NOT"}},{"term":{"organization":"NOT"}},{"term":{"keywords":"NOT"}},{"term":{"github.description":"NOT"}},{"term":{"github.readme":"NOT"}},{"query_string":{"query":"NOT"}}]}},"sort":[{"_score":{}}]}]]; nested: QueryParsingException[Failed to parse query [NOT]]; nested: ParseException[Cannot parse 'NOT': Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; nested: ParseException[Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; }{[Q8hNolH5QJ2EtpZNcls6GA][scaladex][4]: RemoteTransportException[[Abe Brown][local[1]][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":10,"query":{"bool":{"should":[{"term":{"repository":"NOT"}},{"term":{"organization":"NOT"}},{"term":{"keywords":"NOT"}},{"term":{"github.description":"NOT"}},{"term":{"github.readme":"NOT"}},{"query_string":{"query":"NOT"}}]}},"sort":[{"_score":{}}]}]]; nested: QueryParsingException[Failed to parse query [NOT]]; nested: ParseException[Cannot parse 'NOT': Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; nested: ParseException[Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; }
scaladexJVM 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
scaladexJVM 	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
scaladexJVM 	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
scaladexJVM 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:855)
scaladexJVM 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:833)
scaladexJVM 	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:387)
scaladexJVM 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
scaladexJVM 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
scaladexJVM 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
scaladexJVM 	at java.lang.Thread.run(Thread.java:745)
scaladexJVM Caused by: [scaladex] QueryParsingException[Failed to parse query [NOT]]; nested: ParseException[Cannot parse 'NOT': Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ]; nested: ParseException[Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     ];
scaladexJVM 	at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:246)
scaladexJVM 	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
scaladexJVM 	at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:116)
scaladexJVM 	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
scaladexJVM 	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:303)
scaladexJVM 	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:206)
scaladexJVM 	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:201)
scaladexJVM 	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
scaladexJVM 	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:838)
scaladexJVM 	at org.elasticsearch.search.SearchService.createContext(SearchService.java:654)
scaladexJVM 	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:620)
scaladexJVM 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:371)
scaladexJVM 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
scaladexJVM 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
scaladexJVM 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
scaladexJVM 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
scaladexJVM 	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
scaladexJVM 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
scaladexJVM 	... 3 more
scaladexJVM Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'NOT': Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     
scaladexJVM 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:122)
scaladexJVM 	at org.apache.lucene.queryparser.classic.MapperQueryParser.parse(MapperQueryParser.java:848)
scaladexJVM 	at org.elasticsearch.index.query.QueryStringQueryParser.parse(QueryStringQueryParser.java:227)
scaladexJVM 	... 20 more
scaladexJVM Caused by: org.apache.lucene.queryparser.classic.ParseException: Encountered "<EOF>" at line 1, column 3.
scaladexJVM Was expecting one of:
scaladexJVM     <BAREOPER> ...
scaladexJVM     "(" ...
scaladexJVM     "*" ...
scaladexJVM     <QUOTED> ...
scaladexJVM     <TERM> ...
scaladexJVM     <PREFIXTERM> ...
scaladexJVM     <WILDTERM> ...
scaladexJVM     <REGEXPTERM> ...
scaladexJVM     "[" ...
scaladexJVM     "{" ...
scaladexJVM     <NUMBER> ...
scaladexJVM     <TERM> ...
scaladexJVM     "*" ...
scaladexJVM     
scaladexJVM 	at org.apache.lucene.queryparser.classic.QueryParser.generateParseException(QueryParser.java:698)
scaladexJVM 	at org.apache.lucene.queryparser.classic.QueryParser.jj_consume_token(QueryParser.java:580)
scaladexJVM 	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:265)
scaladexJVM 	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:171)
scaladexJVM 	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:160)
scaladexJVM 	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:117)
scaladexJVM 	... 22 more
scaladexJVM 

```

**Comment by MasseGuillaume** [comment]
The doc suggest we use https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#query-dsl-simple-query-string-query

I think when I tried it was no giving me the same result as the plain query-string. Maybe we need to turn some flag on: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#_flags

**Comment by fsalvi** [comment]
I guess you already know, but scaladex crashes with many special characters:
- [ ( : {

**Comment by MasseGuillaume** [comment]
this is where to start looking:
https://github.com/scalacenter/scaladex/blob/master/server/src/main/scala/ch.epfl.scala.index.server/Api.scala#L58
